import hashlib
from datetime import date, datetime
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_document_id(
    patient_name: str,
    medical_aid_number: str,
    coopland_score: int,
) -> str:
    raw = f"{patient_name}|{medical_aid_number}|{coopland_score}|{datetime.utcnow().date()}"
    return hashlib.sha256(raw.encode()).hexdigest()[:10]


def generate_hrantn_pdf(
    *,
    output_path: Path,
    patient_name: str,
    medical_aid_number: str,
    plan_name: str,
    gestational_age_weeks: float,
    booking_category: str,  # ANTN1A / ANTN1B
    coopland_score: int,
    risk_band: str,
    risk_drivers: list,
    extra_consults: int,
    extra_ultrasounds: int,
):
    """
    Generate HRANTN authorisation request PDF
    aligned to Discovery requirements.
    """

    c = canvas.Canvas(str(output_path), pagesize=A4)
    width, height = A4

    y = height - 40

    def line(text):
        nonlocal y
        c.drawString(40, y, text)
        y -= 18

    # -------------------------------------------------
    # Header
    # -------------------------------------------------
    doc_id = generate_document_id(patient_name, medical_aid_number, coopland_score)

    c.setFont("Helvetica-Bold", 14)
    line("Discovery Health - HRANTN Authorisation Request")
    y -= 10

    c.setFont("Helvetica", 10)
    line(f"Date: {date.today().isoformat()}")
    line(f"Document ID: {doc_id}")
    y -= 10

    # -------------------------------------------------
    # Patient details
    # -------------------------------------------------
    c.setFont("Helvetica-Bold", 11)
    line("Patient Details")
    c.setFont("Helvetica", 10)

    line(f"Patient Name: {patient_name}")
    line(f"Medical Aid Number: {medical_aid_number}")
    line(f"Plan: {plan_name}")
    line(f"Gestational Age at Assessment: {gestational_age_weeks:.1f} weeks")
    line(f"Booking Category: {booking_category}")

    y -= 10

    # -------------------------------------------------
    # Risk classification
    # -------------------------------------------------
    c.setFont("Helvetica-Bold", 11)
    line("Risk Classification (Modified Coopland)")
    c.setFont("Helvetica", 10)

    line(f"Coopland Score: {coopland_score}")
    line(f"Risk Band: {risk_band}")

    y -= 5
    line("Clinical Risk Drivers:")
    for driver in risk_drivers:
        label = driver.replace("_", " ").title()
        line(f"  - {label}")

    y -= 10

    # -------------------------------------------------
    # Requested authorisation
    # -------------------------------------------------
    c.setFont("Helvetica-Bold", 11)
    line("Requested HRANTN Authorisation")
    c.setFont("Helvetica", 10)

    line(f"Additional Consultations Requested: {extra_consults}")
    line(f"Additional Ultrasounds Requested: {extra_ultrasounds}")
    line(f"Tariff Code: 6999 Rule C - HRANTN")

    y -= 10

    # -------------------------------------------------
    # Declaration
    # -------------------------------------------------
    c.setFont("Helvetica-Bold", 11)
    line("Declaration")
    c.setFont("Helvetica", 10)

    declaration_lines = [
        "This patient has been assessed using the Modified Coopland Risk",
        "Scoring System and meets the criteria for additional antenatal",
        "consultations and ultrasound scans as indicated above.",
        "",
        "The attending practitioner confirms that:",
        "  1. The risk factors listed are clinically verified.",
        "  2. The additional consultations are medically necessary.",
        "  3. The patient has been counselled regarding their risk profile.",
    ]
    for dl in declaration_lines:
        line(dl)

    y -= 20

    # -------------------------------------------------
    # Signature block
    # -------------------------------------------------
    c.setFont("Helvetica", 10)
    line("_" * 40 + "          " + "_" * 20)
    line("Practitioner Signature                     Date")
    y -= 10
    line("_" * 40 + "          " + "_" * 20)
    line("Practice Number                            HPCSA Number")

    y -= 20

    # -------------------------------------------------
    # Footer
    # -------------------------------------------------
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(40, 30, f"Doc ID: {doc_id} | "
                 "Generated by NOH Maternal Pricing Tool | "
                 f"Coopland Score: {coopland_score} | "
                 f"Risk Band: {risk_band} | "
                 f"{date.today().isoformat()}")

    c.save()
    return output_path


# ============================================================
# CLI test harness
# ============================================================

if __name__ == "__main__":
    out = Path("outputs")
    out.mkdir(exist_ok=True)

    path = generate_hrantn_pdf(
        output_path=out / "test_hrantn_request.pdf",
        patient_name="Jane Doe",
        medical_aid_number="DH-123456789",
        plan_name="Classic",
        gestational_age_weeks=14.0,
        booking_category="ANTN1A",
        coopland_score=5,
        risk_band="MEDIUM",
        risk_drivers=["chronic_hypertension", "previous_cs"],
        extra_consults=2,
        extra_ultrasounds=1,
    )
    print(f"PDF generated: {path}")
